### ISSUE TITLE
Request: graduated healing based on difficulty and age

### ISSUE THREAD

**Issue by Divineaspect** [rockhymas/iberia#12]
I love difficulty which isn't grindy/manual. So Iberia's slow healing appeals to me. 
However it's too much of a good thing, especially in light of DWC. Once someone has a blaze rod to make healing potions, they can already get back to their base.

I request the Linking of healing rate to two factors, difficulty mode, and age in the world. 

I propose that you heal 9 hearts per night at base on easy, 5 on medium, and 3 on hard/hardcore. 
This is reduced by 1 health (half a heart) for every X minutes you've been alive in your present incarnation, to a minimum of 1.

This effective "Vigor of Youth" boost to healing would increase survivibility and would make getting restarted after DWC feasible.

alternate approaches to resolve this would include other methods of gaining instant healing or regeneration without access to the nether.

**Comment by rockhymas** [comment]
I like the idea of basing healing on the world difficulty level and will add that. Given the philosophy of Iberia though, adjusting it based on "age" or time in game doesn't fit. In play testing, I really like that injuries lay you out for a few days, even in the early game. It encourages building up a small base with early game materials, since you have time on your hands while healing.
