### ISSUE TITLE
Hard Stone causes a huge amount of lag upon generating

### ISSUE THREAD

**Issue by erindal** [rockhymas/iberia#15]
My system specs:
ASUS motherboard
FX-6300 3.5 GHz AMD CPU
12 GB of RAM
GTX 760 2 GB
HDD

Upon generating a new world with the hardened stone enabled, I get a massive amount of lag, it usually drops me to around 9-15 FPS. If I had to guess I'd say its because of all the stone getting turned into hardened stone.

If I let it sit and generate, the lag usually decreases (although it never seems to completely go away).

This is easily reproducible on my own system, not sure if anyone else has this issue.

**Comment by rockhymas** [comment]
I've noticed lag when starting a new world (or going to a new area) as well. Thanks for filing the issue, I'll use it to change hard stone to replace stone at world gen, rather than having to update on tick. Then hard stone won't reform if re-surrounded. It will only go one direction, and should reduce lag further.
